name: better_mood

version: 0.0.1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  firebase_analytics:
  firebase_auth:

flutter:
  uses-material-design: true
