name: better_mood

version: 0.0.1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  async: ^2.2.0
  charts_flutter: ^0.6.0
  cloud_firestore: ^0.12.2
  emoji_picker: ^0.0.2
  firebase_analytics: ^3.0.2
  firebase_auth: ^0.11.1+5
  firebase_core: ^0.4.0+3
  firebase_database: ^3.0.2
  firebase_storage: ^3.0.1
  flutter_calendar: ^0.0.8
  flutter_crashlytics: ^1.0.0
  flutter_datetime_picker: ^1.2.1
  flutter_facebook_login: ^2.0.1
  flutter_markdown: ^0.2.0
  google_sign_in: ^4.0.2
  image_picker: ^0.6.0+9
  intl: ^0.15.8
  path: ^1.6.2
  path_provider: ^0.5.0+1
  webview_flutter: ^0.3.9+1

flutter:
  uses-material-design: true
  assets:
    - assets/
